export const projects = [
  {
    title: 'Live Weather Forecast',
    description: "Developed a real-time weather app for cities, providing users with live updates on temperature, humidity, visibility, and wind speed using advanced technology.",
    image: '/images/7.jpg',
    tags: [ "React.js", "Node.js", "Express.js"],
    source: 'https://github.com/RaviiSharma/Live-Weather-Forecast',
    visit: 'https://ravi-live-weather.netlify.app/',
    id: 6,
  },
  {
    title: 'News App',
    description: "Developed a news app with a login page and perform authentication using firebase and used react-router-dom for routing used bootstrap forimplementing the cards section. Axios for fetching data from news API after successful login.",
    image: '/images/8.jpg',
    tags: [ "React.js", "Node.js", "Express.js"],
    source: 'https://github.com/RaviiSharma/News-app',
    visit: 'https://ravi-news-app.netlify.app/',
    id: 7,
  },
  {
    title: 'Todo App',
    description: "App used to maintain our day-to-day tasks and It is helpful in planning our daily schedules.",
    image: '/images/6.webp',
    tags: ['React.js', 'Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/RaviiSharma/To_Do-App',
    visit: 'https://ravii-todo-app.netlify.app/',
    id: 5,
  }, 
  {
    title: 'Naukri Portal',
    description: "Developed the backend of a website like Naukri.com which registers companies and students looking for internships and job opportunities",
    image: '/images/9.jpg',
    tags: ['Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/RaviiSharma/Naukri-portal',
    visit: 'https://github.com/RaviiSharma/Naukri-portal',
    id: 7,
  },
  {
    title: 'Book Management',
    description: "Created a Book Management backend like Goodreads.com with 10 multiple APIs like user registration, Login, Book publishing, Book review, and rating Like library management, etc.",
      image: '/images/3.webp',
      tags: ['Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/RaviiSharma/Project-Books-Managament',
    visit: 'https://github.com/RaviiSharma/Project-Books-Managament',
    id: 2,
  },
  {
    title: 'Grocery Store',
    description: "Using JavaScript, Node.js, Express & MongoDB to Create a Grocery Website backend with multiple APIs for products. Like BigBasket, Blinkit etc.",
    image: '/images/5.webp',
    tags: ['Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/RaviiSharma/Grocery-Store-BackEnd',
    visit: 'https://github.com/RaviiSharma/Grocery-Store-BackEnd',
    id: 4,
  },
  {
    title: 'Amazon Clone',
    description:"Built an eCommerce website backend with JWT authentication and AWS S3 integration, featuring multiple product APIs and user cart and order management.",
    image: '/images/1.png',
    tags: ['Node.js', 'MongoDB', 'Express.js.'],
    source: 'https://github.com/RaviiSharma/ECommerce/tree/project5-ecommerce',
    visit: 'https://github.com/RaviiSharma/ECommerce/tree/project5-ecommerce',
    id: 0,
  },
  {
    title: 'Blogging Website',
    description: "Create a blog website where users can write some blogs and other users can see this blog. Here use JWT authentication for protected APIs. Like One Magazine and URBANBEARDSMAN.",
    image: '/images/4.png',
    tags: ['Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/RaviiSharma/project-Blogging-Site/tree/blogging-site-project',
    visit: 'https://github.com/RaviiSharma/project-Blogging-Site/tree/blogging-site-project',
    id: 3,
  },
  {
    title: 'Tiny URL Clone',
    description: "Built a website using ShortId for URL shortening and Redis for caching, similar to Bitly and TinyURL.",
      image: '/images/2.jpg',
      tags: ['Node.js', 'MongoDB', 'Express.js.'],
    source: 'https://github.com/RaviiSharma/urlShortner/tree/project/urlShortnerGroup41',
    visit: 'https://github.com/RaviiSharma/urlShortner/tree/project/urlShortnerGroup41',
    id: 1,
  },
  
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2021, text: 'Graduated as a mechanical engineer', },
  { year: 2022, text: 'Joined as backend developer trainee at functionUp', },
  { year: 2023, text: 'Shared my projects with the world', },
 // { year: 2021, text: 'Started my own platform', },
];